# Generated by Django 5.2.1 on 2025-05-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0003_login_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sobrenome',
        ),
    ]
