# Generated by Django 5.2.1 on 2025-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0004_remove_usuario_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='exemplo@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='1234', max_length=255),
            preserve_default=False,
        ),
    ]
