# Generated by Django 5.2.1 on 2025-05-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0005_usuario_email_usuario_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(default='Bairro Exemplo', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='EX', max_length=2),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localidade',
            field=models.CharField(default='Cidade Exemplo', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='logradouro',
            field=models.CharField(default='Rua Exemplo', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_residencia',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
