# Generated by Django 5.2.1 on 2025-05-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0007_categoria_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='localidade',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='EX', max_length=255),
        ),
    ]
