# Generated by Django 5.2.1 on 2025-05-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0008_remove_usuario_localidade_alter_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='localidade',
            field=models.CharField(default='Cidade Exemplo', max_length=255),
        ),
    ]
