# Generated by Django 5.2.1 on 2025-05-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0010_alter_usuario_bairro_alter_usuario_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_cartao', models.CharField(max_length=16)),
                ('validade', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHome.usuario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHome.produto')),
            ],
        ),
    ]
