# Generated by Django 5.2.1 on 2025-06-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0012_alter_categoria_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
