# Generated by Django 5.2.1 on 2025-06-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0014_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cvv',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_compra',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='numero_cartao',
            field=models.IntegerField(max_length=16),
        ),
    ]
